### ISSUE TITLE
strange dependency

### ISSUE THREAD

**Issue by stiv-yakovenko** [liveontologies/elk-reasoner#40]
RandomWalkIncrementalClassificationWithABoxTask depends on ClassAndIndividualAxiomTrackingLoader,  which is incorrect, because test should depend on module, not module on test.

**Comment by ykazakov** [comment]
The elk-benchmark package is severely outdated.
It does not compile at the moment and has more serious dependency problems than you mention.
Just don't use it. It is not listed among the modules of elk-parent and is not required for the functionality of ELK.
