### ISSUE TITLE
Inquiry on logging

### ISSUE THREAD

**Issue by rwynne** [liveontologies/elk-reasoner#57]
What is the correct way to disable 'INFO' logging while instantiating the reasoner?

pr 29, 2019 6:45:58 PM org.semanticweb.elk.reasoner.tracing.TraceState <init>
INFO: elk.reasoner.tracing.evictor=org.semanticweb.elk.util.collections.RecencyEvictor(16896,0.750000)
Apr 29, 2019 6:45:58 PM org.semanticweb.elk.reasoner.stages.ClassExpressionQueryState <init>
INFO: elk.reasoner.classexpressionquery.evictor = org.semanticweb.elk.util.collections.RecencyEvictor(512,0.750000)
Apr 29, 2019 6:45:58 PM org.semanticweb.elk.reasoner.stages.EntailmentQueryState <init>
INFO: elk.reasoner.entailmentquery.evictor = org.semanticweb.elk.util.collections.RecencyEvictor(512,0.750000)
Apr 29, 2019 6:45:58 PM org.semanticweb.elk.reasoner.Reasoner <init>
INFO: ELK reasoner was created
Apr 29, 2019 6:45:59 PM org.semanticweb.elk.util.logging.LoggerWrap log
INFO: Context Reset started
Apr 29, 2019 6:45:59 PM org.semanticweb.elk.reasoner.stages.AbstractReasonerStage execute
INFO: Context Reset using 8 workers
Apr 29, 2019 6:45:59 PM org.semanticweb.elk.util.logging.LoggerWrap log

**Comment by ykazakov** [comment]
You can set the desired log level in Protege 5.5 Preferences:
![](https://user-images.githubusercontent.com/488607/54447456-b2ffdf80-4706-11e9-85b2-8cef1b96745d.png)

**Comment by rwynne** [comment]
Sorry I should had been more specific.  I am using the OWLAPI for this specific task.

**Comment by ykazakov** [comment]
@rwynne have you checked the [wiki](https://github.com/liveontologies/elk-reasoner/wiki/ElkOwlApi#disabling-logging-messages)?

**Comment by rwynne** [comment]
@ykazakov I see now, yes- works perfectly.  Thanks!

```
import org.apache.log4j.*;
...
LogManager.getLogger("org.semanticweb.elk").setLevel(Level.ERROR);
```
