### ISSUE TITLE
Disable ELK Warnings in Protege?

### ISSUE THREAD

**Issue by rwynne** [liveontologies/elk-reasoner#63]
Is it possible to disable these? The unsupported features are encountered frequently after reasoning my ontologies. They are benign and don't affect users' work, with the exception of the amount of time necessary to select each checkbox and OK. I'm using Protege 5.5.0-beta7. Thanks!

**Comment by ykazakov** [comment]
@rwynne Which version of ELK are you using? Are you referring to pop-up windows in Protege? The new (unreleased) version of ELK should print the messages to the [Log view of Protege 5.5.0](https://github.com/protegeproject/protege-distribution/releases/tag/v5.5.0).
You can either build ELK from sources or use the [nightly builds](https://github.com/liveontologies/elk-reasoner/wiki/GettingElk).  The nightly builds are a bit outdated (the CI broke a few years ago) but should not have popup warnings, as far as I remember.

**Comment by rwynne** [comment]
@ykazakov Yes, these are the pop-up windows.
My plugin folder shows version 0.4.3.

The first two are related to DataHasValue and subDataPropertyOf.
The next suggests configuration changes through Preferences. I will try this in addition to the nightly build.

**Comment by ykazakov** [comment]
I guess the problem has been resolved. If not, please reopen.
