### ISSUE TITLE
ELK 0.5 apparently erroneously claims that it implements `OBJECT_PROPERTY_HIERARCHY` InferenceType

### ISSUE THREAD

**Issue by matentzn** [liveontologies/elk-reasoner#66]
For context see https://github.com/ontodev/robot/pull/999#issuecomment-1666567017

Given this ontology here:

```
Prefix: : <http://x.org/>

Ontology: <http://purl.obolibrary.org/obo/test>

Class: C
Class: O
   DisjointWith: C

ObjectProperty: P
  Domain: C
ObjectProperty: Q
  Domain: O
    SubPropertyOf: P
```

ELK 0.43 used to recognise that 

a Class Expression `Q some X` would be unsatisfiable. ELK 0.5 does not. Its possible I have not looked deeply enough, but leaving this here for documentation.

**Comment by ykazakov** [comment]
How do you test satisfiability of the class expression? In OWL API? 4 or 5? Could you share the code?
I did a quick test in Protege using the DL query tab with the latest build of ELK (from the repo) and it shows me "Equivalent classes (1 of 1) owl:Nothing".
Just a silly question: how to get ELK 0.5? ;-)

**Comment by matentzn** [comment]
Hey @ykazakov!

Here is the failing test:

https://github.com/ontodev/robot/blob/542775905f721111329b181ac49549a181c5f0ec/robot-core/src/test/java/org/obolibrary/robot/ReasonerHelperTest.java#L54

Here is the approach: https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/ReasonerHelper.java#L72 (inject OWL class expressions in for loop).

This row returned something with ELK 0.43:
https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/ReasonerHelper.java#L86

This is the PR where I am trying to migrate ROBOT to ELK 0.5:
https://github.com/ontodev/robot/pull/999/files

Thanks for taking a look!

**Comment by ykazakov** [comment]
OK, I found ELK 0.5 here:
https://repo1.maven.org/maven2/au/csiro/elk-distribution-protege/0.5.0/
However, I cannot reproduce the problem in Protege. Everything seems normal:

<img width="605" alt="Screenshot 2023-08-07 at 11 25 12" src="https://github.com/liveontologies/elk-reasoner/assets/2140361/84ee8da3-b347-42dd-8853-8aa6791a1264">

**Comment by ykazakov** [comment]
Hmm.. I tried to follow your approach and added a fresh class:

Class: Q-domain
    EquivalentTo:
        Q some owl:Thing

ELK 0.5 in Protege shows me correctly that it is unsatisfiable.
I would appreciate a minimal running example reproducing the problem.

**Comment by matentzn** [comment]
Yes you are right, the plugin seems to work fine.. Maybe the behaviour of reasoner.flush() changed?

https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/ReasonerHelper.java#L83

I will play a bit with that and see what I can find.

**Comment by ykazakov** [comment]
Well, Protege also uses `reasoner.flush()`, and whenever I add and delete the `Q-domain` class in Protege (with incremental mode or not), the reasoner results seem to be updated correctly.

**Comment by ykazakov** [comment]
Of course, Protege uses OWL API 4, so there could be a difference between OWL API 4 and OWL API 5.

**Comment by matentzn** [comment]
@ykazakov I think I chased it down.

This row: https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/ReasonerHelper.java#L51

Basically, the ELK claims that in implements PROPERTY_HIERARCHY, but this here:

https://github.com/ontodev/robot/blob/master/robot-core/src/main/java/org/obolibrary/robot/ReasonerHelper.java#L57

Does not return anything. According to HermiT, `Q` in the example above is unsatisfiable. 

So in my view, I think `OBJECT_PROPERTY_HIERARCHY` should be removed from the list of implemented `InferenceType`s.

**Comment by ykazakov** [comment]
@matentzn ELK *does* support computation of property hierarchy, it is just incomplete. Basically it computes the same hierarchy as the asserted hierarchy in Protege. I do not think it is right to remove it from `reasoner.getPrecomputableInferenceTypes()`. If so, one should also remove the class hierarchy from there since it can be also incomplete (i.e., when the ontology is not EL).

As a workaround, you could additionally test if checking consistency of object property is supported: declare a property with domain `owl:Nothing` and if the reasoner says that it is consistent, use your translation.

**Comment by matentzn** [comment]
I am totally out of touch with the logic, but for the profile that ELK explicitly supports, is it true that `OBJECT_PROPERTY_HIERARCHY` is complete? My take would be that the point of `getPrecomputableInferenceTypes` is that for the profile the reasoner implements, the service is implemented completely? Or do you disagree?

**Comment by ykazakov** [comment]
As I understand, precomputable reasoning types have nothing to do with supported reasoning types or their completeness. These are just reasoning types for which the results (complete or incomplete) can be precomputed all in one shot.

As far as I can tell, in OWL API one cannot tell or check which profiles a reasoner support (completely). I think it is not even possible to check if an ontology belongs to a particular profile. Also, ELK does not fully support any OWL API profile. For the OWL EL profile, for example, it is currently incomplete for datatypes, nominals, self restriction. Also, the OWL profile specification does not tell much about support of reasoning tasks, such as object property computation. For example, it is not clear, whether an OWL EL reasoner should be able to check if an object property is transitive or reflexive, or to compute domain or ranges of object properties.

**Comment by matentzn** [comment]
Ok, your call :) I will close this issue then - nothing important enough to argue about! Thanks as always for the discussion though!
