### ISSUE TITLE
Version 0.5

### ISSUE THREAD

**Issue by mosfet80** [liveontologies/elk-reasoner#68]
the latest version, 0.4.3, was released several years ago. If possible, it would be very useful to release a 0.5 version

**Comment by ykazakov** [comment]
This seems to be a duplicate of https://github.com/liveontologies/elk-reasoner/issues/48.

**Comment by ykazakov** [comment]
This seems to be a duplicate of https://github.com/liveontologies/elk-reasoner/issues/48.

**Comment by ykazakov** [comment]
This seems to be a duplicate of https://github.com/liveontologies/elk-reasoner/issues/48.
